FUNCTION (SetSolutionFolder arg1)
  IF (MSVC)
    SET(SolutionFolder "${arg1}")
    FOREACH (Target ${ARGV})
      IF (NOT "${Target}" STREQUAL "${SolutionFolder}")
        SET_TARGET_PROPERTIES("${Target}" PROPERTIES FOLDER "${SolutionFolder}")
      ENDIF ()
    ENDFOREACH ()
  ENDIF (MSVC)
ENDFUNCTION (SetSolutionFolder)
